version: '3'
volumes:
  static:
  pgdata:
  users:
services:
  python: &python

    #    image: python:3.7
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - static:/app/static
      - users:/app/users
    ports:
      - 8000:8000
    command: pipenv run gunicorn -w 4 decisionTree.wsgi -b 0.0.0.0:8000
    #    command: cd /app && pip install pipenv && pipenv shell && python manage.py runserver
    depends_on:
      - rabbitmq
      - postgres
      - celery_worker
  nginx:
    #    image: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - python
  rabbitmq:
    image: rabbitmq:3.7-alpine
  celery_worker:
    <<: *python
    command: pipenv run celery -A decisionTree worker -l info
    ports: []
    volumes:
      - users:/app/users
    depends_on:
      - rabbitmq
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: decisionTree
      POSTGRES_DB: decisionTree
      POSTGRES_PASS: decisionTree
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432