# Generated by Django 2.2.4 on 2019-08-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('error_message', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(
                    choices=[('Error', 'Error'), ('Running', 'Running'), ('Finished', 'Finished'),
                             ('Created', 'Created')], default='Created', max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('config_file_name', models.CharField(max_length=50)),
                ('data_file_name', models.CharField(max_length=50)),
                ('result_directory_path', models.CharField(blank=True, max_length=50)),
                ('user',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiment',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_iteration', models.IntegerField(blank=True)),
                ('runs', models.IntegerField(blank=True)),
                ('mean_time', models.FloatField(blank=True)),
                ('last_iter_number', models.IntegerField(blank=True)),
                ('experiment',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='decisionTreeCore.Experiment')),
            ],
        ),
    ]
