# Generated by Django 2.2 on 2019-04-30 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(
                    choices=[('P', 'Pending'), ('E', 'Error'), ('R', 'Running'), ('F', 'Finished'), ('C', 'Created')],
                    default='C', max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('config_file', models.CharField(max_length=50)),
                ('data_file_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
