# Generated by Django 2.2 on 2019-04-30 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('decisionTreeCore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiments',
            old_name='config_file',
            new_name='config_file_name',
        ),
        migrations.AddField(
            model_name='experiments',
            name='result_file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
