# Generated by Django 2.2 on 2019-04-30 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decisionTreeCore', '0002_auto_20190430_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Error', 'Error'), ('Running', 'Running'),
                                                     ('Finished', 'Finished'), ('Created', 'Created')], default='C',
                                            max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('config_file_name', models.CharField(max_length=50)),
                ('data_file_name', models.CharField(max_length=50)),
                ('result_file_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Experiments',
        ),
    ]
