# Generated by Django 2.2.4 on 2019-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('decisionTreeCore', '0003_experiment_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='iteration',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AddField(
            model_name='experiment',
            name='last_iter_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='mean_time',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.CharField(
                choices=[('Error', 'Error'), ('Running', 'Running'), ('Canceled', 'Canceled'), ('Finished', 'Finished'),
                         ('Created', 'Created')], default='Created', max_length=15),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
