# Generated by Django 2.2.4 on 2019-09-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('decisionTreeCore', '0004_auto_20190905_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='last_iter_number',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='mean_time',
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField(blank=True)),
                ('iteration', models.IntegerField(blank=True, default=1000)),
                ('last_iter_number', models.IntegerField(blank=True, default=0)),
                ('mean_time', models.FloatField(blank=True, default=0)),
                ('experiment',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='decisionTreeCore.Experiment')),
            ],
        ),
    ]
