# Generated by Django 2.2 on 2019-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('decisionTreeCore', '0004_experiment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.CharField(
                choices=[('Pending', 'Pending'), ('Error', 'Error'), ('Running', 'Running'), ('Finished', 'Finished'),
                         ('Created', 'Created')], default='Created', max_length=15),
        ),
    ]
