# Generated by Django 2.2 on 2019-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('decisionTreeCore', '0005_auto_20190501_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='result_file_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
