# Generated by Django 2.2.5 on 2019-09-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('decisionTreeCore', '0006_auto_20190905_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='names_file_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='experiment',
            name='test_file_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
