# Generated by Django 2.2.5 on 2019-09-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('decisionTreeCore', '0008_auto_20190923_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='names_file_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='test_file_name',
            field=models.CharField(max_length=50),
        ),
    ]
