# Generated by Django 2.2.5 on 2019-10-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('decisionTreeCore', '0009_auto_20190923_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.BooleanField(default=True)),
                ('edit', models.BooleanField(default=True)),
                ('download_output', models.BooleanField(default=True)),
                ('download_input', models.BooleanField(default=True)),
                ('share', models.BooleanField(default=True)),
                ('experiment',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='decisionTreeCore.Experiment')),
            ],
        ),
    ]
