export const GET_EXPERIMENTS = "GET_EXPERIMENTS";
export const DELETE_EXPERIMENTS = "DELETE_EXPERIMENTS";
export const ADD_EXPERIMENTS = "ADD_EXPERIMENTS";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGES = "CREATE_MESSAGES";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";