export const GET_EXPERIMENTS = "GET_EXPERIMENTS";
export const DELETE_EXPERIMENTS = "DELETE_EXPERIMENTS";
export const ADD_EXPERIMENTS = "ADD_EXPERIMENTS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGES = "CREATE_MESSAGES";